"""Constantes numéricas y límites tolerados para cálculo y presentación."""

CERO_EPSILON = 1e-9
TOLERANCIA_COINCIDENCIA_FRACCION = 1e-6
DECIMALES_VISUALIZACION = 4
TOLERANCIA_VERIFICACION_SOLUCION = 1e-4
TOLERANCIA_FRACCION_VISUALIZACION = 1e-4

LIMITE_RECONSTRUCCION_FRACCION = 1000
LIMITE_RECONSTRUCCION_ESTRICTA = 10**6
LIMITE_VISUALIZACION_FRACCION = 1000
LIMITE_DENOMINADOR_LATEX = 100

DIMENSION_MAXIMA_INVERSA = 50
DIMENSION_MAXIMA_LATEX_INVERSA = 8

LONGITUD_MAXIMA_CADENA_NUMERO = 256

MSJ_NOTACION_CIENTIFICA_NO_SOPORTADA = (
    "Notación científica no soportada. Escribe el número con decimales o fracción."
)
MSJ_NUMERO_DEMASIADO_LARGO = (
    f"El número excede la longitud máxima permitida ({LONGITUD_MAXIMA_CADENA_NUMERO} caracteres)."
)
